apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.db.persistence.azureFile.storageClassName | default "azure-file" }}
provisioner: kubernetes.io/azure-file
parameters:
  skuName: {{ .Values.db.persistence.azureFile.skuName | default "Premium_LRS" }}
  location: {{ .Values.db.persistence.azureFile.location | default "westeurope" }}
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict
  - actimeo=30
{{- if .Values.db.persistence.azureFile.allowVolumeExpansion }}
allowVolumeExpansion: {{ .Values.db.persistence.azureFile.allowVolumeExpansion }}
{{- end }}
{{- if .Values.db.persistence.azureFile.reclaimPolicy }}
reclaimPolicy: {{ .Values.db.persistence.azureFile.reclaimPolicy }}
{{- end }}
